name: Bugs / Exploits
description: Report a problem
title: ''
labels: Bug-Unconfirmed
assignees: ''
issue_body: true
body:
- type: dropdown
  attributes:
    label: World the issue occured in
    description: Your current world can be found in the player tab list
    options:
      - Main
      - Main (Nether)
      - Main (The End)
      - Minigames-E
      - Minigames-T
      - Player Shops
      - Plots
      - Utility
    validations:
      required: true

- type: input
  attributes:
    label: Location
    description: Please provide either the coordinates or a notable location at/near the issue (if applicable)
    placeholder: "-3956, 72, 593 OR Death Run Nether"
  validations:
    required: false

- type: input
  attributes:
    label: My Minecraft username
  validations:
    required: true

- type: textarea
  attributes:
    label: What I was doing before/when the issue occurred
    placeholder: "I was the killer in the Death Run map and pushed the pressure plate"
  validations:
    required: true

- type: textarea
  attributes:
    label: What happened
    description: "What exactly was the issue?"
    placeholder: "The pressure plate broke but nothing happened"
  validations:
    required: true

- type: textarea
  attributes:
    label: What was supposed to happen
    placeholder: "Something should've happened after the pressure plate broke"
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      ### Please provide any additional details, if any, that should be noted (pictures/videos of it happening, etc)
