name: Grief Report
description: Report a potential grief at a specific location
title: Grief Report
labels: Grief Report
assignees: ''
issue_body: true
body:
- type: input
  attributes:
    label: My Minecraft username
    placeholder: JasonHorkles
  validations:
    required: true

- type: input
  attributes:
    label: The coordinates at the location of the grief
    placeholder: "-3956, 72, 593"
  validations:
    required: true

- type: textarea
  attributes:
    label: What happened
    description: You may provide screenshots of the damage
  validations:
    required: true
